services:
  mysql8:
    image: mysql:8.0.44
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    ports:
      - "13316:3306"